version: '3.8'

services:
  db:
    image: postgres:15
    container_name: alltogether-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: BaseD@ta2025
      POSTGRES_DB: Alltogether
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: alltogether-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/Alltogether
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: BaseD@ta2025

volumes:
  pgdata:
